site_name: Ensuro Protocol
nav:
  - Home: index.md
  - Interfaces:
    - IPolicyPool: interfaces/IPolicyPool.md
    - IEToken: interfaces/IEToken.md
    - IRiskModule: interfaces/IRiskModule.md
    - IPremiumsAccount: interfaces/IPremiumsAccount.md
    - IPolicyHolder: interfaces/IPolicyHolder.md
    - IPolicyPoolComponent: interfaces/IPolicyPoolComponent.md
    - ILPWhitelist: interfaces/ILPWhitelist.md
    - ICooler: interfaces/ICooler.md
    - IUnderwriter: interfaces/IUnderwriter.md
  - Core contracts:
    - PolicyPool: PolicyPool.md
    - EToken: EToken.md
    - PremiumsAccount: PremiumsAccount.md
    - RiskModule: RiskModule.md
  - Base contracts:
    - PolicyPoolComponent: PolicyPoolComponent.md
    - Reserve: Reserve.md
  - Underwriters:
    - FullTrustedUW: underwriters/FullTrustedUW.md
    - FullSignedUW: underwriters/FullSignedUW.md
  - Extensions:
    - Cooler: Cooler.md
    - LPManualWhitelist: LPManualWhitelist.md
  - Libraries:
    - Policy: Policy.md
    - ETKLib: ETKLib.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - solidity
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
